apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: replybot
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/Accurate0/replybot.git
    path: kubernetes
    kustomize:
      images:
        - replybot=ghcr.io/accurate0/replybot:${ARGOCD_APP_REVISION}
  destination:
    server: https://kubernetes.default.svc
    namespace: replybot
operation:
  initiatedBy:
    username: github-actions
  sync:
    prune: true
    syncStrategy:
      hook: {}
