version: '3.8'
services:
  replybot:
    build: .
    container_name: replybot-task
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: replybot-cache
