version: "3.8"
services:
  replybot:
    build:
      context: .
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - REPLYBOT_REDIS_CONNECTION_STRING
      - REPLYBOT_INTERACTION_TABLE_NAME=ReplybotInteraction
      - REPLYBOT_INTERACTION_TABLE_USER_INDEX_NAME=DiscordIdIndex
