version: '3.8'
services:
  replybot:
    build:
      context: .
      args:
        BUILD_MODE: dev
        BUILD_DIRECTORY: debug
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - REPLYBOT_REDIS_CONNECTION_STRING=rediss://:ee75229b88d04c33af3b1e7a1f2bc51b@lenient-anemone-30211.upstash.io:30211
      - REPLYBOT_INTERACTION_TABLE_NAME=ReplybotInteraction
      - REPLYBOT_INTERACTION_TABLE_USER_INDEX_NAME=DiscordIdIndex
    container_name: replybot-task
    depends_on:
      - redis
    links:
      - "redis:replybot-cache"

  redis:
    image: redis:alpine
    container_name: replybot-cache
    ports:
      - 6379:6379
