apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: replybot-secret
  namespace: replybot
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 900
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: replybot-n-ea3
        envSlug: prod
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedSecretReference:
    secretName: replybot-managed-secrets
    secretNamespace: replybot
    creationPolicy: "Owner"
