name: deploy
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: modify config
        run: |
          sed -i 's/\[DISCORD_TOKEN\]/${{ secrets.DISCORD_BOT_TOKEN }}/' config.json
          sed -i 's/\[OPENAI_KEY\]/${{ secrets.OPENAI_API_KEY }}/' config.json

      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/replybot

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy container
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws ecs update-service --region ap-southeast-2 --cluster replybot-cluster --service replybot-service --force-new-deployment
