name: deploy
on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: configure oicd aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ${{ vars.AWS_ECR_REGISTRY }}

      - uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ vars.AWS_ECR_REGISTRY }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: configure oicd aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: deploy container
        run: aws ecs update-service --region ${{ vars.AWS_REGION }} --cluster default-cluster --service replybot-service --force-new-deployment 2>&1 1>/dev/null
