name: deploy
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: configure oicd aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AWS_ECR_REGISTRY }}

      - uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ secrets.AWS_ECR_REGISTRY }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy container
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws ecs update-service --region ap-southeast-2 --cluster default-cluster --service replybot-service --force-new-deployment 2>&1 1>/dev/null
