name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      packages: write

    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache@v4
        with:
          path: app-target
          key: ${{ runner.os }}-app-target-${{ hashFiles('**/Cargo.lock') }}-replybot

      - name: inject /app/target into docker
        uses: reproducible-containers/buildkit-cache-dance@v3.1.2
        with:
          cache-source: app-target
          cache-target: /app/replybot-build/target/

      - uses: actions/cache@v4
        with:
          path: cargo-registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}-replybot

      - name: inject /usr/local/cargo/registry/ into docker
        uses: reproducible-containers/buildkit-cache-dance@v3.1.2
        with:
          cache-source: cargo-registry
          cache-target: /usr/local/cargo/registry/

      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/accurate0/replybot:latest,ghcr.io/accurate0/replybot:${{ github.sha }}
          build-args: |
            BINARY_NAME=replybot
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      # This ugly bit is necessary if you don't want your cache to grow forever
      # till it hits GitHub's limit of 5GB.
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    needs: build
    uses: Accurate0/workflows/.github/workflows/deploy-app-k8s.yaml@main
    with:
      application-name: replybot
    secrets:
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
